ScheduleBatch/src/objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <label>Author</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ScheduleBatch/src/objects/BooksToWriters__c.object
<CustomObject>
    <fields>
        <fullName>Books__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Writers</relationshipLabel>
        <relationshipName>BooksToWriters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Writers__c</fullName>
        <label>Writer</label>
        <referenceTo>Writer__c</referenceTo>
        <relationshipLabel>Books</relationshipLabel>
        <relationshipName>BooksToWriters</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BooksToWriters</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>BooksToWriters Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BooksToWriters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ScheduleBatch/src/objects/Writer__c.object
<CustomObject>
    <fields>
        <fullName>Writers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Writer</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Writers</relationshipLabel>
        <relationshipName>Writers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Writer</label>
    <nameField>
        <label>Writer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Writers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ScheduleBatch/src/classes/book_writersProccessing.cls
global class book_writersProccessing implements Database.Batchable<SObject>, Database.Stateful {

	private Integer JunctionCount = 0;

	global book_writersProccessing() {

	}

	global Database.QueryLocator start(Database.BatchableContext context) {
		return Database.getQueryLocator('SELECT Id, Author__c FROM Book__c WHERE IsBookNeedToBeProceed__c = TRUE');
	}

	global void execute(Database.BatchableContext context, List<Book__c> scope) {
		Set<String> book_writers = new Set<String> ();
		for (Book__c book : scope) {
			book_writers.add(book.Author__c); 
		}
		List<Writer__c> writers = [SELECT Id, Name FROM Writer__c WHERE Name = :book_writers];
		List<BooksToWriters__c> book_to_writers_list = addBooksAndWritersToBookToWritersList(writers, scope);
		upsert scope;
		upsert book_to_writers_list;
	}

	private List<BooksToWriters__c> addBooksAndWritersToBookToWritersList(List<Writer__c> writers, List<Book__c> scope) {
		List<BooksToWriters__c> book_to_writers_list = new List<BooksToWriters__c> ();
		for (Book__c book : scope) {
			for (Writer__c writer : writers) {
				BooksToWriters__c junction_object = new BooksToWriters__c();
				if (book.Author__c == writer.Name) {
					book.IsBookNeedToBeProceed__c = false;
					junction_object.Writers__c = writer.Id;
					junction_object.Books__c = book.Id;
					JunctionCount++;
					book_to_writers_list.add(junction_object);
				}
			}
		}
		return book_to_writers_list;
	}

	global void finish(Database.BatchableContext context) {
		Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
		message.toAddresses = new String[] { 'igor.igorovuich@gmail.com' };
		message.optOutPolicy = 'FILTER';
		message.subject = 'Junction';
		message.plainTextBody = 'Has been created ' + JunctionCount + ' junction objects.';
		Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage> { message };
		Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
		if (results[0].success) {
			System.debug('The email was sent successfully.');
		} else {
			System.debug('The email failed to send: ' + results[0].errors[0].message);
		}
	}
}